# Generated by Django 3.0.5 on 2021-10-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20211011_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ismanager',
            field=models.BooleanField(default=False),
        ),
    ]
