# Generated by Django 3.0.5 on 2021-10-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jariyo', '0002_auto_20211006_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
