# Generated by Django 3.0.5 on 2021-10-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jariyo', '0004_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='sit_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sit_2_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sit_4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sit_4_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sit_over4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sit_over4_max',
            field=models.IntegerField(),
        ),
    ]
