# Generated by Django 3.0.5 on 2021-10-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jariyo', '0008_auto_20211012_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('R', 'Restaurant'), ('C', 'Cafe')], max_length=1),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sit_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sit_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sit_over4',
            field=models.IntegerField(default=0),
        ),
    ]
