# Generated by Django 3.0.5 on 2021-10-15 11:35

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jariyo', '0009_auto_20211013_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='main_photo',
            field=models.ImageField(upload_to='', verbose_name=account.models.Photo),
        ),
    ]
