# Generated by Django 3.0.5 on 2021-10-15 11:49

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jariyo', '0010_auto_20211015_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_path),
        ),
    ]
