# Generated by Django 3.0.5 on 2021-10-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jariyo', '0012_shop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='sit_2_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sit_4_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sit_over4_max',
            field=models.IntegerField(default=0),
        ),
    ]
